language: node_js

node_js:
  - '12'

dist: trusty
sudo: false

addons:
 ssh_known_hosts:
 - 159.65.118.249

before_install: 
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
  - openssl aes-256-cbc -K $encrypted_e92badce6860_key -iv $encrypted_e92badce6860_iv
    -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - cd apiApp

install:
  - npm i

script: 
  - npm test

deploy:
- provider: script
  skip_cleanup: true
  script: "../.travis/deploy.sh"
  on:
    branch: master