language: node_js
node_js:
- '12'
addons:
  ssh_known_hosts: 159.65.118.249
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- cd apiApp
install:
- npm i
script:
- npm test
deploy:
  provider: script
  skip_cleanup: true
  script: 
  - rsync -r $TRAVIS_BUILD_DIR worker@159.65.118.249:web/education-docker 
  - ssh worker@159.65.118.249 'cd web/education-docker && docker-compose up -d --build'
  on:
    branch: main
