version: "3"
services:
  api:
    build: ./apiApp
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: server-api
  client:
    build: ./webUI/client
    ports:
      - "80:80"
    container_name: client
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_base
    ports:
      - 3308:3306